version: 7
profiles:
  - options:
      cwd: /home/chm/
      env: {}
      command: sshpass
      args:
        - '-p'
        - hmchen
        - ssh
        - chm@alps-vm
    type: local
    icon: fas fa-server
    color: '#613d7c'
    name: alps-vm
    id: local:custom:alps-vm:21e254e7-922e-496a-83de-74b78091ee1d
  - options:
      cwd: /home/yjn/music-fox
      env: {}
      command: ./musicfox
    name: music-fox
    type: local
    icon: fas fa-music
    color: '#E51100'
    id: local:custom:8d1220cc-aadd-4519-ae57-ea288df264ac
  - type: ssh
    icon: fas fa-desktop
    options:
      host: ''
      algorithms: {}
      input: {}
      jumpHost: ssh:custom:aliyun:22ecfd15-f228-4ff3-a18a-763640a773c4
      privateKeys: []
    weight: -1
    name: root@:22
    id: ssh:custom:root@:22:9e227e91-a263-44a4-9a6c-dce470a9c242
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy: []
  paste:
    - Ctrl-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
    - Ctrl-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial: []
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
    - Alt-L
  pane-nav-up:
    - Ctrl-Alt-Up
    - Alt-K
  pane-nav-left:
    - Ctrl-Alt-Left
    - Alt-H
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  pane-nav-down:
    - Ctrl-Alt-Down
    - Alt-J
  reconnect-tab: []
  disconnect-tab: []
  group-selectors: {}
  scroll-page-up:
    - Alt-PageUp
  scroll-page-down:
    - Alt-PageDown
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  fontSize: 16
  font: MesloLGS NF
  customColorSchemes:
    - name: OceanicMaterial
      foreground: '#eceff1'
      background: rgba(38, 50, 56, 1)
      cursor: '#FFCC00'
      colors:
        - '#000000'
        - '#D62341'
        - '#9ECE58'
        - '#FAED70'
        - '#396FE2'
        - '#BB80B3'
        - '#2DDAFD'
        - '#d0d0d0'
        - rgba(255, 255, 255, 0.2)
        - '#FF5370'
        - '#C3E88D'
        - '#FFCB6B'
        - '#82AAFF'
        - '#C792EA'
        - '#89DDFF'
        - '#ffffff'
  autoOpen: true
  showTabProfileIcon: true
  lightColorScheme:
    name: OceanicMaterial
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  bell: visual
ssh:
  knownHosts:
    - host: aliyun
      port: 9331
      type: ecdsa-sha2-nistp256
      digest: q6Uc8kYi+gspPDlM53gkzmW1dCLLDgh4WU6XRvVv7HU=
    - host: aliyun
      port: 22
      type: ecdsa-sha2-nistp256
      digest: RLkS0CXZtfxjh2yodVyS2wUABtfa7/JdrINLpOH/V5k=
    - host: 43.137.2.25
      port: 22
      type: ecdsa-sha2-nistp256
      digest: K32IGee96vpmDJgcko1ksofbal/p7TTelCEIJyhqX1Y=
clickableLinks:
  modifier: ctrlKey
accessibility: {}
appearance:
  opacity: 0.83
  frame: native
  colorSchemeMode: light
hacks: {}
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
recoverTabs: false
providerBlacklist: []
commandBlacklist: []
groups: []
profileBlacklist: []
configSync:
  parts: {}
  configID: 23786
  auto: true
enableAutomaticUpdates: false
language: zh-CN
